apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
bases:
- ../../../my-app-base
patchesStrategicMerge:
- headless.yaml
- mongo-sts.yaml
- pers-volume.yaml
- secret.yaml
